# Generated by Django 3.1.7 on 2021-03-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pwd', '0002_auto_20210319_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwd',
            name='SNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
