# Generated by Django 3.1.7 on 2021-11-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exercise_Category', '0001_initial'),
        ('Exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ex_Date', models.DateTimeField()),
                ('Ex_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_requests_created', to='Exercise_Category.exercise_category')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_requests_created', to='Exercise.exercise')),
            ],
        ),
    ]
